title: 팀 텝!
logo: https://github.com/TEAMTEB/tebserver/blob/main/%ED%85%9D%20%EB%A1%9C%EA%B3%A0%20%EB%85%B8%EB%B0%B0%EA%B2%BD.png?raw=true
description: 디스코드를 더욱더 즐겁게하는 봇을 만드는 팀 텝입니다!
theme: jekyll-theme-minimal
